services:
  authentik-server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.8.4}
    container_name: authentik-server
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_db_password
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
    depends_on:
      - authentik-redis
      - authentik-db
    networks:
      - authentik
      - proxy
    ports:
      - ${COMPOSE_PORT_HTTP:-9000}:9000
      - ${COMPOSE_PORT_HTTPS:-9443}:9443
    volumes:
      - /srv/data/authentik/media:/media
      - /srv/data/authentik/templates:/templates
    secrets:
      - authentik_db_password
      - authentik_secret_key

  authentik-worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.8.4}
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_db_password
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
    depends_on:
      - authentik-redis
      - authentik-db
    networks:
      - authentik
    user: root
    volumes:
      - /srv/data/authentik/media:/media
      - /srv/data/authentik/templates:/templates
      - /srv/data/authentik/certs:/certs
    secrets:
      - authentik_db_password
      - authentik_secret_key

  authentik-db:
    image: postgres:16-alpine
    container_name: authentik-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD_FILE: /run/secrets/authentik_db_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - authentik
    secrets:
      - authentik_db_password

  authentik-redis:
    image: redis:8-alpine
    container_name: authentik-redis
    restart: unless-stopped
    volumes:
      - authentik-redis:/data
    networks:
      - authentik

secrets:
  authentik_db_password:
    environment: AUTHENTIK_DB_PASSWORD
  authentik_secret_key:
    environment: AUTHENTIK_SECRET_KEY

networks:
  proxy:
    name: caddy-proxy
    external: true
  authentik:
    name: authentik
    internal: true

volumes:
  authentik-redis:
  postgres-data:
