services:
  miniserve:
    image: svenstaro/miniserve:latest
    container_name: miniserve
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /srv/data/miniserve:/data
    command: >
      /data --mkdir --rm-files --upload-files --interfaces 0.0.0.0 --port 8080
    networks:
      - proxy

networks:
  proxy:
    name: caddy-proxy
    external: true
